### ISSUE TITLE
Panic with current prometheus libs

### ISSUE THREAD

**Issue by TheTincho** [prometheus/mysqld_exporter#251]
Hi,

While packaging 0.10.0 for Debian, I get a panic during tests. We don't use vendoring as a general rule, and checking the versions in vendor.json, I suspect this might be caused by newer versions of the prometheus libraries (client lib, or client_model). It would be very helpful for us if you could update your vendoring and fix these issues. As it is, we are not able to upgrade the mysql exporter to the current release.

Thanks.

```
Errors:

  * /build/prometheus-mysqld-exporter-0.10.0+ds/obj-x86_64-linux-gnu/src/github.com/prometheus/mysqld_exporter/collector/collector_test.go 
  Line 20: - runtime error: invalid memory address or nil pointer dereference 
  goroutine 104 [running]:
  panic(0x82a180, 0xb00070)
        /usr/lib/go-1.9/src/runtime/panic.go:491 +0x283
  github.com/prometheus/mysqld_exporter/collector.readMetric(0x0, 0x0, 0xc4203cb9a0, 0x8aa76b, 0x3)
        /build/prometheus-mysqld-exporter-0.10.0+ds/obj-x86_64-linux-gnu/src/github.com/prometheus/mysqld_exporter/collector/collector_test.go:20 +0x40
  github.com/prometheus/mysqld_exporter/collector.TestScrapeSlaveStatus.func2()
        /build/prometheus-mysqld-exporter-0.10.0+ds/obj-x86_64-linux-gnu/src/github.com/prometheus/mysqld_exporter/collector/slave_status_test.go:40 +0x12c
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
        /build/prometheus-mysqld-exporter-0.10.0+ds/obj-x86_64-linux-gnu/src/github.com/jtolds/gls/context.go:97 +0x463
  github.com/jtolds/gls.EnsureGoroutineId.func1()
        /build/prometheus-mysqld-exporter-0.10.0+ds/obj-x86_64-linux-gnu/src/github.com/jtolds/gls/gid.go:24 +0x31
  github.com/jtolds/gls._m(0x0, 0xc4203cba20)
        /build/prometheus-mysqld-exporter-0.10.0+ds/obj-x86_64-linux-gnu/src/github.com/jtolds/gls/stack_tags.go:74 +0x31
  github.com/jtolds/gls.github_com_jtolds_gls_markS(0x0, 0xc4203cba20)
        /build/prometheus-mysqld-exporter-0.10.0+ds/obj-x86_64-linux-gnu/src/github.com/jtolds/gls/stack_tags.go:54 +0x35
  github.com/jtolds/gls.addStackTag(0x0, 0xc4203cba20)
        /build/prometheus-mysqld-exporter-0.10.0+ds/obj-x86_64-linux-gnu/src/github.com/jtolds/gls/stack_tags.go:49 +0x3a
  github.com/jtolds/gls.EnsureGoroutineId(0xc420426de0)
        /build/prometheus-mysqld-exporter-0.10.0+ds/obj-x86_64-linux-gnu/src/github.com/jtolds/gls/gid.go:24 +0xc9
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc42004b660, 0xc420426d80, 0xc4203cb9e0)
        /build/prometheus-mysqld-exporter-0.10.0+ds/obj-x86_64-linux-gnu/src/github.com/jtolds/gls/context.go:63 +0x177
  github.com/prometheus/mysqld_exporter/collector.TestScrapeSlaveStatus(0xc42025ca50)
        /build/prometheus-mysqld-exporter-0.10.0+ds/obj-x86_64-linux-gnu/src/github.com/prometheus/mysqld_exporter/collector/slave_status_test.go:38 +0xb91
  testing.tRunner(0xc42025ca50, 0x8c78d8)
        /usr/lib/go-1.9/src/testing/testing.go:746 +0xd0
  created by testing.(*T).Run
        /usr/lib/go-1.9/src/testing/testing.go:789 +0x2de
```

**Comment by SuperQ** [comment]
I've been planning to do a release soon, which would give us a chance to update vendoring.

**Comment by TheTincho** [comment]
Hey Ben, any news on this?

**Comment by SuperQ** [comment]
Sorry, been busy with lots of stuff.  I have a couple of fixes, maybe I can get a release done before/at FOSDEM.

**Comment by TheTincho** [comment]
It seems to me this was fixed with #262?

**Comment by SuperQ** [comment]
Yea, I need to cut an official release. :-)

**Comment by TheTincho** [comment]
Actually, I now see that I still get the same panic. I am using the released version of client_golang (and you have a newer vendored version), but that might not be the difference.. I don't really know how to track this down, these panics are not that helpful.. :/

**Comment by TheTincho** [comment]
After spending some time on this trying to understand the stack trace.. I noticed there is a test failure at the bottom, and now I think the panic is just because the channel was closed without sending any metrics (and so it is not really the problem)..

```
        slave_status_test.go:27: error calling function on test: all expectations were already fulfilled, call to query 'SHOW SLAVE STATUS' with args [] was not expected
```

I tracked that message down to sqlmock, of which I am using an older version. Updating to 1.3.0 solved the issue. Sorry for the noise..
