### ISSUE TITLE
External dependencies for tests prevents build

### ISSUE THREAD

**Issue by Berbe** [prometheus/mysqld_exporter#493]
* Host operating system: `4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux`
* mysqld_exporter version: [0.12.1](https://github.com/prometheus/mysqld_exporter/releases/tag/v0.12.1)

### What did you do that produced an error?
Compiling through `gbp buildpackage --git-builder='debuild -e GOPATH -i -I -uc -us'`

### What did you expect to see?
Successful build of Debian packages

### What did you see instead?
The [`exporter_test.go`](https://github.com/prometheus/mysqld_exporter/blob/48667bf7c3b438b5e93b259f3d17b70a7c9aff96/collector/exporter_test.go) integration test introduced in #228 requires an external dependency, while some other tests like [`global_status_test.go`](https://github.com/prometheus/mysqld_exporter/blob/48667bf7c3b438b5e93b259f3d17b70a7c9aff96/collector/global_status_test.go) use a mock connection, which seems better.

Enforcing strong dependencies with other components make the code less portable, being specifically tailored to your compilation farm abilities.
```
>> building binaries
GO111MODULE=on /usr/src/jenkins/go/bin/promu build --prefix /usr/src/jenkins/build
 >   prometheus-mysqld-exporter
>> running all tests
GO111MODULE=on go test -race  -mod=vendor ./...
ok  	github.com/prometheus/mysqld_exporter	5.510s
...
3 total assertions

...
6 total assertions

.....
11 total assertions

...
14 total assertions


14 total assertions

time="2020-08-06T11:06:30Z" level=error msg="Error pinging mysqld: dial tcp 127.0.0.1:3306: connect: connection refused" source="exporter.go:146"

14 total assertions

.x
Failures:

  * /usr/src/jenkins/build/collector/exporter_test.go 
  Line 78:
  Expected '999' to be between '5.5' and '10.3' or equal to one of them (but it wasn't)!
  goroutine 41 [running]:
  github.com/prometheus/mysqld_exporter/collector.TestGetMySQLVersion.func1()
  	/usr/src/jenkins/build/collector/exporter_test.go:78 +0x205
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
  	/usr/src/jenkins/build/vendor/github.com/jtolds/gls/context.go:97 +0x59b
  github.com/jtolds/gls.EnsureGoroutineId.func1()
  	/usr/src/jenkins/build/vendor/github.com/jtolds/gls/gid.go:24 +0x46
  github.com/jtolds/gls._m(0x0, 0xc00024c480)
  	/usr/src/jenkins/build/vendor/github.com/jtolds/gls/stack_tags.go:108 +0x43
  github.com/jtolds/gls.github_com_jtolds_gls_markS(0x0, 0xc00024c480)
  	/usr/src/jenkins/build/vendor/github.com/jtolds/gls/stack_tags.go:56 +0x43
  github.com/jtolds/gls.addStackTag(0x0, 0xc00024c480)
  	/usr/src/jenkins/build/vendor/github.com/jtolds/gls/stack_tags.go:49 +0x48
  github.com/jtolds/gls.EnsureGoroutineId(0xc0001f5590)
  	/usr/src/jenkins/build/vendor/github.com/jtolds/gls/gid.go:24 +0x136
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc0000627c0, 0xc0001f5530, 0xc00024c440)
  	/usr/src/jenkins/build/vendor/github.com/jtolds/gls/context.go:63 +0x299
  github.com/prometheus/mysqld_exporter/collector.TestGetMySQLVersion(0xc0001c8700)
  	/usr/src/jenkins/build/collector/exporter_test.go:73 +0xdc
  testing.tRunner(0xc0001c8700, 0xbe7ba8)
  	/usr/lib/go-1.11/src/testing/testing.go:827 +0x163
  created by testing.(*T).Run
  	/usr/lib/go-1.11/src/testing/testing.go:878 +0x65a
  


16 total assertions

--- FAIL: TestGetMySQLVersion (0.00s)
..........................
42 total assertions

..........
52 total assertions

....
56 total assertions

..
58 total assertions

......................
80 total assertions

.....
85 total assertions

....
89 total assertions

.......
96 total assertions

......
102 total assertions

.
103 total assertions

......
109 total assertions

.........
118 total assertions

......................
140 total assertions

............
152 total assertions

..............
166 total assertions

..............
180 total assertions

..
182 total assertions

..
184 total assertions

....
188 total assertions

FAIL
FAIL	github.com/prometheus/mysqld_exporter/collector	0.110s
make[1]: *** [Makefile.common:152: common-test] Error 1
make[1] : on quitte le répertoire « /usr/src/jenkins/build »
dh_auto_build: make -j1 returned exit code 2
make: *** [debian/rules:18: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -i -I failed
gbp:error: 'debuild -e GOPATH -i -I -uc -us' failed: it exited with 29
```

**Comment by SuperQ** [comment]
You need to pass `-short` to the testing to skip the external dependencies.
